name: 'Setup Build Environment'
description: 'Sets up build tools, dev libraries, and other dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.31.4'

    - name: Set up Clang
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        sudo apt install libc++-17-dev libc++abi-17-dev

    - name: Install other dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install libomp-17-dev