# This is a basic workflow to help you get started with Actions

name: Build Pytorch with Clang

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TORCH_VERSION: v2.2.1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common_repo_setup

      - name: Setup venv
        shell: bash
        run: |
          python3 -m venv ~/venv
          . ~/venv/bin/activate

      - name: Download Pytorch source, install requirements, and build
        run: |
          wget https://github.com/pytorch/pytorch/releases/download/$TORCH_VERSION/pytorch-$TORCH_VERSION.tar.gz
          tar xf pytorch-$TORCH_VERSION.tar.gz
          cd pytorch-$TORCH_VERSION
          pip install networkx==2.8.8
          pip install -r requirements.txt
          CC=clang-17 CXX=clang++-17 CXXFLAGS="-std=c++20 -stdlib=libc++" python setup.py bdist_wheel
          ls dist/

      - uses: actions/upload-artifact@v4
        with:
          name: pytorch-wheel
          path: pytorch-$TORCH_VERSION/dist/*.whl


